# -*- coding: utf-8 -*-
"""mapaCovid19.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaQiR9c1zwQVxTD8NitLtR0WNcO8UolQ

**Plotando marcadores em mapa interativo**

Após termos:
- Recuperado os Dados do COVID-19 da API do site https://brasil.io e tratarmos eles no artigo https://www.linkedin.com/pulse/consumindo-api-e-tratando-dados-com-python-alexandre-tavares/
- Enriquecermos os Dados com as coordenadas das Cidades / Estados no artigo https://www.linkedin.com/pulse/enriquecimento-de-dados-alexandre-tavares/

Vamos Agora marcar no mapa as cidades com casos/mortes por COVID-19 e ao clicarmos exibir a quantidade de casos confirmados e mortes.

**Instala Biblioteca de Mapas**
"""

!pip install folium

"""**Inicializa Bibliotecas**"""

import folium
import pandas as pd
from folium import plugins

"""**Lendo Dataset**

Faça o Upload do Arquivo do dataset da mesma forma ensinada no artigo:
- https://www.linkedin.com/pulse/enriquecimento-de-dados-alexandre-tavares/
"""

dfCodiv19 = pd.read_csv('datasetCodiv19Enriquecido.csv',encoding ='utf-8', sep=';')

"""**Exibir data frama**

Exibe os primeiros 10 registros do data frame
"""

dfCodiv19.head(10)

"""**Criando Mapa**

Cria o mapa com as coordenadas do Brasil
"""

mapa = folium.Map(
    location=[-9.0458683,-60.5283577],
    tiles='Stamen Terrain',
    zoom_start=4
)

"""**Inserir Marcadores no Mapa**

Com as coordenadas que agregamos em nossa base vamos marcar os Pontos e exibir as informações do Covid-19
"""

for i,codv in dfCodiv19.iterrows():
  folium.Marker(
      [codv['Latitude'], codv['Longitude']],
      popup='<i>' + codv['Cidade'] + '/' + codv['Estado'] + '</i><br/>Confirmados: ' + str(codv['casosConfirmados']), 
      tooltip=codv['Cidade'] + '/' + codv['Estado']
      ).add_to(mapa)

mapa

"""**Gerando HTML do mapa**"""

mapa.save('mapaCodiv19.html')

"""Os scripts deste artigo estão em: https://github.com/AleTavares/pyEnriqueceDados

**Autor:**

Alexandre Tavares

Engenheiro de Dados

https://www.linkedin.com/in/alexandre-tavares/
"""

